repos:
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.2
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
