# Generated by Django 5.0.3 on 2024-04-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonogram",
            name="puzzle_solution",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
