# Generated by Django 5.0.3 on 2024-04-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0002_nonogram_puzzle_solution"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonogram",
            name="image",
            field=models.ImageField(default="", upload_to="nonogram_images/"),
            preserve_default=False,
        ),
    ]
