# Generated by Django 5.0.3 on 2024-04-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0003_nonogram_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nonogram",
            name="difficulty_level",
            field=models.IntegerField(
                choices=[(1, "★"), (2, "★★"), (3, "★★★"), (4, "★★★★"), (5, "★★★★★")],
                default=3,
            ),
        ),
    ]
