# Generated by Django 5.0.3 on 2024-04-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0004_alter_nonogram_difficulty_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nonogram",
            name="puzzle_solution",
            field=models.JSONField(null=True),
        ),
    ]
